# Setup
title:               Kireeti
tagline:             ''
description:         'Simple personal website'
url:                 https://kir-7.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Kireeti
  url:               https://x.com/kireeti___
  email:             kkireeti1@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
